services:
  server:
    image: jmdirksen/minecraft-java
    container_name: minecraft-java
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./minecraft:/minecraft
    environment:
      - EULA=true
      - motd=Example Minecraft Server
      - difficulty=easy
      - level_seed=
      - max_players=20
      - player_idle_timeout=0
      - spawn_protection=16

  stats:
    image: jmdirksen/minecraftstats
    container_name: minecraftstats
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./minecraft:/minecraft
    environment:
      - INTERVAL=300
      - INACTIVE_DAYS=30
      - MIN_PLAYTIME=15
