services:
  server:
    image: jmdirksen/minecraft-java
    container_name: minecraft-java
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - minecraft-java:/minecraft
    environment:
      - EULA=true
      - motd=Example Minecraft Server
      - difficulty=easy
      - level-seed=
      - max-players=20
      - player-idle-timeout=0
      - spawn-protection=16

volumes:
  minecraft-java:
